title: id3s3c@cyberspace
email: id3s3c@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  welcome to my notes, infosec/it/hacking related
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: id3s3c
github_username:  id3s3c

# Build settings

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

dash:
  date_format: "%b %-d, %Y"

  social_links:
    - url: https://x.com/id3s3c
      icon: twitter-square
      color: cyan
    - url: https://linkedin.com/in/id3s3c
      icon: linkedin
      color: blue
    - url: https://www.twitch.tv/id3s3c
      icon: twitch
      color: purple
    - url: https://github.com/id3s3c
      icon: github-square
      color: yellow

  show_author: true

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false


theme: jekyll-dash
plugins:
  - jekyll/tagging
  - jekyll-paginate